### ISSUE TITLE
Return 400 is app_ver, app_id, version are invalid

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/kinto-amo#8]
Spawned from #3

**Comment by Natim** [comment]
The AMO blocklist XML page never returns a 400, do you have an example of when you'd like to have this behavior?

**Comment by leplatrem** [comment]
> The AMO blocklist XML page never returns a 400

Ok then, let's mimic what it does there. But if we cast values to `int()` we'll return a 500 which is not ideal

**Comment by Natim** [comment]
> If we cast values to int() we'll return a 500 which is not ideal

I have written a test about that to make sure it never happens, see: https://github.com/mozilla-services/kinto-amo/blob/master/kinto_amo/tests/test_views.py#L25-L29

**Comment by leplatrem** [comment]
Well done!
